import "./globals.css";
import { Poppins } from "next/font/google";

import clsx from "clsx";
import Layout from "@/components/Layout";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "Bendando",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "bg-gradient-to-b from-slate-950 to-indigo-900 flex flex-col min-h-screen"
        )}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
